
find_path(JERRYSCRIPT_INCLUDE_DIR jerryscript.h)
find_library(JERRYSCRIPT_CORE_LIBRARY jerry-core)
find_library(JERRYSCRIPT_EXT_LIBRARY jerry-ext)
find_library(JERRYSCRIPT_LIBM_LIBRARY jerry-libm)
find_library(JERRYSCRIPT_PORT_DEFAULT_LIBRARY jerry-port-default)
set(JERRYSCRIPT_INCLUDE_DIRS "${JERRYSCRIPT_INCLUDE_DIR}" "${JERRYSCRIPT_INCLUDE_DIR}/jerryscript-ext/")
set(JERRYSCRIPT_LIBRARIES "${JERRYSCRIPT_CORE_LIBRARY}" "${JERRYSCRIPT_EXT_LIBRARY}" "${JERRYSCRIPT_LIBM_LIBRARY}" "${JERRYSCRIPT_PORT_DEFAULT_LIBRARY}")
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(JERRYSCRIPT DEFAULT_MSG JERRYSCRIPT_INCLUDE_DIRS JERRYSCRIPT_LIBRARIES)
mark_as_advanced(JERRYSCRIPT_INCLUDE_DIRS JERRYSCRIPT_LIBRARIES)

